export default {
  // categories
  FETCH_CATEGORIES: 'FETCH_CATEGORIES',

  // posts
  FETCH_POSTS_BY_CATEGORY: 'FETCH_POSTS_BY_CATEGORY',
  FETCH_ALL_POSTS: 'FETCH_ALL_POSTS',

  // post
  ADD_POST: 'ADD_POST',
  FETCH_POST: 'FETCH_POST',
  VOTE_POST: 'VOTE_POST',
  UPDATE_POST: 'UPDATE_POST',
  DELETE_POST: 'DELETE_POST',

  //comments
  FETCH_COMMENTS_BY_POST: 'FETCH_COMMENTS_BY_POST',

  //comment
  ADD_COMMENT: 'ADD_COMMENT',
  FETCH_COMMENT: 'FETCH_COMMENT',
  VOTE_COMMENT: 'VOTE_COMMENT',
  UPDATE_COMMENT: 'UPDATE_COMMENT',
  DELETE_COMMENT: 'DELETE_COMMENT',
  FAILURE: 'FAILURE',
  FETCHING: 'FETCHING',
};
